baseurl                 = "https://australresidency.org/" # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "The Austral Residency"
theme                   = "mas"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/favicon.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "CC BY–NC–ND 4.0 · 2018" # FIXME: Add registered charity number

# Metadata
    description         = "A place of refuge for scientists, writers, documentarians, artists, crafters, and anyone doing work that demands sustained attention in head, heart, and hand." # Max 160 characters show in search results
    primaryImage        = "/images/freeman-corcovado-viewed-from-quellon.png" # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/what"
    text = "what"

[[params.mainMenu]]
    link = "/who"
    text = "who"

#[[params.mainMenu]]
#    link = "/apply"
#    text = "apply"

#[[params.mainMenu]] # For charity registration etc
#    link = "/about"
#    text = "about"

[[params.mainMenu]]
    link = "/credits"
    text = "credits"

#[[params.mainMenu]]
#    link = "/es"
#    text = "en español"
